/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationbiometría_aquino;

import java.awt.Image;
import java.io.File;
import java.io.FileReader;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Virginia Aquino
 */
public class Biometría extends javax.swing.JFrame {

    /**
     * Creates new form Biometría
     */
    public JFileChooser jfcBuscar;
    File archivo;
    String img1;
    String img2;
    
    public Biometría() {
        initComponents();
        
        jfcBuscar=new JFileChooser();
        FileNameExtensionFilter formato= new FileNameExtensionFilter("BMP Images","bmp");
        jfcBuscar.setFileFilter(formato);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_img1 = new javax.swing.JTextField();
        txt_img2 = new javax.swing.JTextField();
        btn_cargarImg1 = new javax.swing.JButton();
        btn_cargarImg2 = new javax.swing.JButton();
        btn_comparar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 96, -1, -1));

        jLabel1.setText("APLICACIÓN BIOMÉTRICA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 11, -1, -1));

        jLabel2.setText("Ruta de Imagen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setText("Ruta de Imagen");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        txt_img1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_img1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 112, -1));
        getContentPane().add(txt_img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 126, -1));

        btn_cargarImg1.setText("Cargar Imagen 1");
        btn_cargarImg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarImg1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cargarImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        btn_cargarImg2.setText("Cargar Imagen 2");
        btn_cargarImg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarImg2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cargarImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        btn_comparar.setText("Comparar Huella");
        btn_comparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compararActionPerformed(evt);
            }
        });
        getContentPane().add(btn_comparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 204, 34));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 122, 220, 360));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 230, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargarImg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarImg1ActionPerformed
        // TODO add your handling code here:
        
        jfcBuscar.showOpenDialog(this);
        archivo=jfcBuscar.getSelectedFile();
        txt_img1.setText(archivo.toString());
        img1=archivo.toString();
        try{
            Image imagen=ImageIO.read(archivo);
            ImageIcon imgicon=new ImageIcon(imagen);
            jLabel4.setIcon(imgicon);
            
        }catch(Exception e){
         JOptionPane.showMessageDialog(null ,"No se pudo cargar la imagen");
            
        }   
    }//GEN-LAST:event_btn_cargarImg1ActionPerformed

    private void btn_compararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compararActionPerformed
        // TODO add your handling code here:
        try{
            boolean found=false;
            FileReader f1= new FileReader(img1);
            FileReader f2= new FileReader(img2);
            while(true){
                int pix1=f1.read();
                int pix2=f2.read();
                
                if(pix1 !=pix2)
                    break;
                if(pix1==-1){
                    found=true;
                    break;
                }
            }
            if(found){
                JOptionPane.showMessageDialog(this,"Es la misma persona");
            }
            else{
                 JOptionPane.showMessageDialog(this,"Es una Persona Diferente");
            }
            
            
        }catch(Exception ex){
         ex.printStackTrace();
            
        }   
    }//GEN-LAST:event_btn_compararActionPerformed

    private void btn_cargarImg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarImg2ActionPerformed
        // TODO add your handling code here:
        jfcBuscar.showOpenDialog(this);
        archivo=jfcBuscar.getSelectedFile();
        txt_img2.setText(archivo.toString());
        img2=archivo.toString();
        try{
            Image imagen=ImageIO.read(archivo);
            ImageIcon imgicon=new ImageIcon(imagen);
            jLabel5.setIcon(imgicon);
            
        }catch(Exception e){
         JOptionPane.showMessageDialog(null ,"No se pudo cargar la imagen");
            
        }   
    }//GEN-LAST:event_btn_cargarImg2ActionPerformed

    private void txt_img1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_img1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_img1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biometría.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biometría.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biometría.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biometría.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biometría().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarImg1;
    private javax.swing.JButton btn_cargarImg2;
    private javax.swing.JButton btn_comparar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_img1;
    private javax.swing.JTextField txt_img2;
    // End of variables declaration//GEN-END:variables
}
